theme: jekyll-theme-cayman
title: Rede Pela Democracia
description: Rede Pela Democracia
show_downloads: "true"
github:
  zip_url: https://www.dropbox.com/s/fkarpvda69ksrp7/MANUALRPD.pdf?dl=0
  tar_url: https://www.dropbox.com/s/fkarpvda69ksrp7/MANUALRPD.pdf?dl=0
  another_url: Rede Pela Democracia
