theme: jekyll-theme-cayman
title: Rede Pela Democracia
description: Rede Pela Democracia
show_downloads: "true"
github:
  zip_url: blob:https://share.riseup.net/740ddd4b-e028-4624-9db2-412fa0cc44f8
  another_url: Rede Pela Democracia
